resolver: lts-9.0
packages:
- .
- location:
    git: https://github.com/haskell-game/sdl2.git
    commit: bc30282eca6c04d1f910f2f3c96b0a64cf84f158
  extra-dep: true
- location:
    git: https://github.com/haskell-game/sdl2-image.git
    commit: ab036e1c91e3cf5fcc89d3d61bd6c2e975c2f38d
  extra-dep: true
- location:
    git: https://github.com/chrisdone/sdl2-cairo.git
    commit: fab0d5128feefe0941336af79d8b3ad63c5db00c
  extra-dep: true
