resolver: lts-22.44
packages:
  - .

extra-deps:
  - cairo-0.13.12.0
  - gtk2hs-buildtools-0.13.12.0
  - html-conduit-1.3.2.2
  - sdl2-cairo-0.2
  - github: EarlGray/cairo-canvas
    commit: 8e031fd5682c5c5d3e7310a4e3ac49f60f193982

allow-newer: true
