name: "build"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "test/html/**"

env:
  GHC_VERSION: "9.6.7"
  MANUAL_CACHE_RESET_BIN: v1
  MANUAL_CACHE_RESET_GHC: v1
  MANUAL_CACHE_RESET_STACK: v1

jobs:
  build:
    name: Build Vado
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set all tracked file modification times to the time of their last commit
        run: |
          rev=HEAD
          for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
              touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
          done

      - uses: ./.github/actions/hs-setup

      - run: stack build

  test:
    name: Test Vado
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set all tracked file modification times to the time of their last commit
        run: |
          rev=HEAD
          for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
              touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
          done

      - uses: ./.github/actions/hs-setup

      - run: stack test --fast
